version: 2

sources:
  - name: jaffle_shop
    database: raw
    tables:
      - name: customers
      - name: orders
      
  - name: stripe
    database: raw
    tables:
      - name: payment
        loaded_at_field: _batched_at::timestamp

        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

  - name: ticket_tailor
    database: raw
    tables:
      - name: orders
      - name: events
      - name: issued_tickets
